#!/bin/bash

DRIVER="ntfs3"

for KVER in `ls -1 $DRIVER | grep "^[0-9]\+\.[0-9]\+"`;
do
    echo "Kernel $KVER:"
    for SYMBOL in `find ./$DRIVER/$KVER/ -name Kconfig`; do
	grep "^config" $SYMBOL | sed -e "s/config /CONFIG_/g"
    done
done
